ryoppippi/ccusage

src/data-loader.ts
This pull request improves the validation of date and month fields in the `src/data-loader.ts` file by introducing stricter regex-based validation for formatting. The changes ensure that these fields conform to expected formats (`YYYY-MM-DD` for dates and `YYYY-MM` for months).
Validation improvements:
* [`src/data-loader.ts`](diffhunk://#diff-cfaeb021b3c268b42cc0a4054c30ac88a397b2a30f38a8ed23f261040d5ed2f5L35-R38): Updated `DailyUsageSchema` to validate the `date` field using a regex pattern that enforces the `YYYY-MM-DD` format.
* [`src/data-loader.ts`](diffhunk://#diff-cfaeb021b3c268b42cc0a4054c30ac88a397b2a30f38a8ed23f261040d5ed2f5L60-R66): Updated `MonthlyUsageSchema` to validate the `month` field using a regex pattern that enforces the `YYYY-MM` format.
=> feat: refactor schema to use regex for date and month

README.md, src/commands/daily.ts, src/commands/monthly.ts, src/commands/session.ts, src/data-loader.test.ts, src/data-loader.ts, src/shared-args.ts, src/types.ts
Feature #11
This PR adds a new `--order` (`-o`) flag to control the sort order of dates in both daily and monthly usage reports. Users can now choose between descending (newest first, default) and ascending (oldest first) order, providing more flexibility in how they view their Claude usage data.
Previously, both daily and monthly reports were hard-coded to display dates in descending order (newest first). While this is often the desired behavior, some users may prefer to see their usage chronologically from oldest to newest, especially when:
- Tracking usage growth over time
- Analyzing historical trends
- Comparing early usage patterns with recent ones
- Generating reports for documentation that should read chronologically
1. **Added `--order` flag to shared arguments** …
=> feat: add sort order support 

src/shared-args.ts
This pull request includes a small change to the `src/shared-args.ts` file. The default sort order for the `sharedArgs` configuration has been updated from "desc" (newest first) to "asc" (oldest first).
=> fix!: order is now asc instead of desc

package.json, tsdown.config.ts
This pull request removes references to the `shared-args` module from the project configuration files. The changes ensure that the module is no longer included in the build process or exported.
Configuration updates:
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L25): Removed the export entry for `./shared-args`, which previously pointed to `./dist/shared-args.js`.
* [`tsdown.config.ts`](diffhunk://#diff-c105f99c241d6d60e41561e663ee096629894e9b2a773c82283655b323f59485R7): Excluded `shared-args.ts` from the entry configuration, preventing it from being included in the build output.
=> chore: stop exporting shared args

bun.lock, package.json, src/data-loader.test.ts, src/data-loader.ts, src/debug.test.ts, src/debug.ts, src/pricing-fetcher.test.ts, src/pricing-fetcher.ts
This pull request refactors the cost calculation logic in the `src/data-loader.ts`, `src/debug.ts`, and associated test files to improve efficiency and maintainability. The key changes include replacing direct pricing cache manipulation with the `PricingFetcher` class, converting synchronous cost calculation functions to asynchronous, and ensuring proper cleanup of resources using the `using` statement.
* **Introduction of `PricingFetcher` class**:
- Replaced direct usage of pricing cache functions (`clearPricingCache`, `fetchModelPricing`, `getModelPricing`) with the `PricingFetcher` class across `src/data-loader.ts` and `src/debug.ts`. This encapsulates pricing logic and simplifies resource management. [[1]](diffhunk://#diff-cfaeb021b3c268b42cc0a4054c30ac88a397b2a30f38a8ed23f261040d5ed2f …
=> feat: class based pricing-fetcher with using syntax

src/data-loader.ts, src/utils.internal.test.ts, src/utils.internal.ts
Close #46
- Replace Object.groupBy usage with manual groupBy implementation
- Add tests for groupBy utility function
- Maintains Node.js 20 compatibility without external polyfill dependencies
=> Replace Object.groupBy with manual implementation for Node.js 20 compatibility

.github/workflows/ci.yaml, README.md, bun.lock, package.json, src/commands/daily.ts, src/commands/mcp.ts, src/commands/monthly.ts, src/commands/session.ts, src/data-loader.test.ts, src/data-loader.ts, src/shared-args.internal.ts
=> Revert "feat!: specify claude dir with `CLAUDE_CONFIG_DIR` and remove `-p`/`--path` option"

.github/workflows/ci.yaml, README.md, bun.lock, package.json, src/commands/daily.ts, src/commands/mcp.ts, src/commands/monthly.ts, src/commands/session.ts, src/data-loader.test.ts, src/data-loader.ts, src/shared-args.internal.ts
=> Revert "Revert "feat!: specify claude dir with `CLAUDE_CONFIG_DIR` and remove `-p`/`--path` option""

CLAUDE.md, README.md, src/mcp.ts
• Add monthly usage report tool to MCP server
• Add 5-hour billing blocks usage report tool to MCP server  
• Update documentation for new MCP tools and blocks command
**New Tools Added:**
- \`monthly\` - Returns monthly usage reports with same parameters as existing tools
- \`blocks\` - Returns 5-hour billing blocks usage reports with billing cycle tracking
**API Consistency:**
- Both tools accept standard parameters: \`since\`, \`until\`, \`mode\`
- JSON output format consistent with existing \`daily\` and \`session\` tools
- Seamless integration with existing MCP client implementations
**CLAUDE.md:**
- Added comprehensive blocks command usage examples
- Updated MCP integration section with all 4 available tools
- Enhanced development commands with MCP server options
- Updated data …
=> feat(mcp): add monthly and blocks tools to MCP server

src/commands/blocks.ts, src/data-loader.ts, src/session-blocks.internal.test.ts, src/session-blocks.internal.ts
- Added --session-length (-l) option to customize session block duration in hours
- Default remains 5 hours for backward compatibility  
- Supports any positive number of hours (including decimals like 2.5)
- Added validation to ensure session length is positive
- Comprehensive test coverage for various duration scenarios
- session-blocks.internal.ts: Made session duration configurable by updating identifySessionBlocks() to accept optional sessionDurationHours parameter
- data-loader.ts: Added sessionDurationHours to LoadOptions and passed through to session block identification
- blocks.ts: Added CLI option with validation and help text
- Added 9 comprehensive tests covering custom durations (1h, 2h, 2.5h, 3h, 24h, 0.5h)
- Tests verify correct block creation, gap detection, and timing
- …
=> feat: add configurable session length to blocks command

CLAUDE.md, src/data-loader.ts, src/debug.ts, src/macro.internal.ts, src/pricing-fetcher.ts, src/types.internal.ts
- Standardize Valibot schema variable names to follow camelCase convention (variables start with lowercase)
- Rename all schema variables from PascalCase to camelCase while keeping type names unchanged
- Add naming conventions documentation to CLAUDE.md
- Fix test command documentation in CLAUDE.md
1. **UsageDataSchema** → **usageDataSchema**
- Main schema for Claude usage data from JSONL files
- Updated in data-loader.ts and debug.ts
2. **ModelBreakdownSchema** → **modelBreakdownSchema**
- Schema for model-specific usage breakdown data
- Updated all array references in other schemas
3. **DailyUsageSchema** → **dailyUsageSchema**
- Schema for daily usage aggregation data
4. **SessionUsageSchema** → **sessionUsageSchema**
- Schema for session-based usage aggregation data
5. …
=> style: standardize schema naming conventions

CLAUDE.md, src/mcp.ts
This PR adds comprehensive test coverage for the MCP (Model Context Protocol) server functionality, covering both stdio and HTTP transport modes.
🚨 **Migration from valibot to zod**: Schema validation now uses zod instead of valibot for better type safety and ecosystem compatibility
🚨 **Migration from fastmcp to @modelcontextprotocol/sdk + Hono by @yusukebe**: 
- Replaced fastmcp with official MCP SDK for better compatibility and future-proofing
- HTTP transport now uses Hono framework by @yusukebe for improved performance and developer experience
- This provides more robust MCP protocol support and better HTTP handling
- **In-Source Testing**: Added tests using the if (import.meta.vitest \!= null) pattern directly in src/mcp.ts
- **Stdio Transport Tests**: Test server creation, tool …
=> feat: add comprehensive MCP server tests

README.md
Updates the documentation URL in README.md from ccusage.ryoppippi.com to ccusage.com
=> docs: update documentation URL to ccusage.com

docs/.vitepress/config.ts
- Changed OGP image format from SVG to PNG in VitePress config
- This ensures the logo displays correctly on social media platforms
Many social platforms (Twitter, Facebook, LinkedIn) do not support SVG format for Open Graph Protocol previews, causing the logo to not display properly when sharing links.
Updated the og:image meta tag to use logo.png instead of logo.svg. The PNG format is universally supported by all major social media platforms.
=> fix: change OGP image from SVG to PNG for better social media compatibility

src/data-loader.ts
- Fixed failing weekly usage tests by updating expectations to match Sunday as the default week start
The weekly usage tests were expecting Thursday as the week start, but the implementation uses Sunday as the default week start. This was causing test failures.
- Updated all test expectations in \`loadWeeklyUsageData\` tests to match Sunday week start:
- Single week test: adjusted dates to ensure they fall within same week
- Multi-week tests: updated expected week start dates  
- Date filter test: corrected expected week for February data
All tests now pass successfully ✅
=> fix: update weekly test expectations to match Sunday as week start

docs/guide/statusline.md, package.json, src/commands/statusline.ts
This PR adds offline mode support to the statusline command and **makes it the default** for optimal performance. The statusline now uses cached pricing data by default, eliminating network latency.
⚠️ **BREAKING**: 
1. The statusline command now accepts CLI arguments (specifically `--offline`/`--no-offline`)
2. **Offline mode is now the default behavior** (previously required network access)
While this changes the command signature and default behavior, existing configurations will continue to work without modification.
- ✨ Add `--offline` flag to statusline command arguments
- 🚀 **Set offline mode as default** for instant response times
- 🔧 Pass offline flag to all data loading functions:
- `loadSessionUsageById()`
- `loadDailyUsageData()`
- `loadSessionBlockData()`
- 📚 Update …
=> fix!: add offline mode support to statusline command

.mcp.json, CLAUDE.md
Replace direct llms.txt URL references with byethrow MCP server access in CLAUDE.md documentation.
- Update Error Handling section to reference byethrow MCP server instead of direct URL
- Add Byethrow MCP to External MCP Servers list with description
- Add byethrow reference to Tips for Claude Code section
- **Error Handling section**: Changed documentation reference from direct llms.txt URL to "Available via byethrow MCP server"
- **MCP Integration section**: Added "Byethrow MCP: Access @praha/byethrow documentation and examples for functional error handling" to the External MCP Servers list
- **Tips for Claude Code section**: Added byethrow entry with MCP server reference
This change ensures consistent access to byethrow documentation through the newly added MCP server integration.
=> docs: update CLAUDE.md to reference byethrow MCP server

src/data-loader.ts
Refactor test code to use fs-fixture getPath() method instead of manual path.join operations. Improves consistency with fs-fixture API usage patterns. All tests continue to pass after refactoring.
=> refactor: use fs-fixture methods instead of manual path operations

README.md, docs/guide/getting-started.md, src/_shared-args.ts, src/_utils.ts, src/commands/blocks.ts, src/commands/daily.ts, src/commands/monthly.ts, src/commands/session.ts, src/commands/weekly.ts
- Added a new `--compact` flag to force compact table layout
- Users can now explicitly enable compact mode for better screenshots and sharing
- The flag works with all commands (daily, monthly, weekly, session)
- Added `compact` boolean flag to shared arguments (without short flag as requested)
- Extended `ResponsiveTable` class with `forceCompact` option
- Updated all command implementations to pass the compact flag from CLI context
- Documentation updated with examples and feature description
- All existing tests pass
- Manually tested with various commands:
- `ccusage --compact`
- `ccusage daily --compact`
- `ccusage monthly --compact`
- `ccusage weekly --compact`
- `ccusage session --compact`
Closes #502
=> feat: add --compact flag for explicit compact mode

config-schema.json, src/_types.ts, src/commands/statusline.ts
- Add support for using session cost data directly from Claude Code's statusline hook input
- Add `costSource` CLI option with three modes: `auto` (default), `ccusage`, and `cc`
- Update statusline hook JSON schema to support optional `cost` field from Claude Code
- Extended `statuslineHookJsonSchema` to include optional `cost` field with `total_cost_usd` and metadata
- Maintains backward compatibility with existing statusline input format
- `auto` (default): Prefer Claude Code cost if available, fallback to ccusage calculation
- `ccusage`: Always calculate using ccusage's token-based calculation
- `cc`: Always use Claude Code's provided cost (show N/A if unavailable)
- Refactored session cost calculation logic to support multiple cost sources
- Added comprehensive tests for new cost …
=> feat(statusline): add costSource option to use Claude Code session cost

docs/guide/statusline.md
Updates the statusline documentation to reflect recent cost source feature additions in PRs #571 and #574.
- **Added comprehensive cost source option documentation** for the new `--cost-source` parameter
- **Updated setup examples** showing how to configure different cost source modes in `settings.json`
- **Enhanced output format examples** including the new "both" mode that displays both Claude Code and ccusage costs
- **Added practical guidance** on when to use each cost source mode
- **Updated component explanations** to reference the new cost source options
- `auto` (default): Prefer Claude Code cost, fallback to ccusage calculation
- `ccusage`: Always use ccusage token-based calculation
- `cc`: Always use Claude Code's pre-calculated cost
- `both`: Display both costs side by side for …
=> docs: update statusline documentation with cost source options

packages/ccusage/README.md, packages/mcp/README.md
Add comprehensive README documentation for the `@ccusage/mcp` package to improve discoverability and usability of the MCP server functionality.
- **Added `packages/mcp/README.md`**: Complete documentation for the MCP package including:
- Quick start instructions with bunx/npx examples
- Claude Desktop integration configuration
- Claude Code MCP setup command
- Reference link to full documentation
- **Updated `packages/ccusage/README.md`**: Added MCP server usage example to the CLI examples section
The MCP package was previously missing user-facing documentation, making it difficult for users to discover and integrate the MCP server with Claude Desktop. This documentation provides essential setup instructions and integration examples.
- Verified README formatting and links
- Confirmed …
=> docs: add README documentation for MCP package

packages/internal/src/pricing.ts
**Fixes critical bug** in statusline context size calculation where Claude 4 models were displaying incorrect context window limits.
The statusline was showing dramatically **incorrect** context sizes for Claude 4 models:
- **Claude Sonnet 4**: Displayed 64K tokens instead of actual 200K context window
- **Claude Opus 4**: Displayed 32K tokens instead of actual 200K context window
This bug caused:
- ❌ Incorrect context utilization calculations in statusline
- ❌ Users seeing wrong context usage percentages
- ❌ Misleading information about available context space
The `getModelContextLimit()` method was **incorrectly** using `max_tokens` (output token limit) instead of `max_input_tokens` (actual context window size) when fetching context limits from LiteLLM pricing data.
**LiteLLM field …
=> fix(internal): fix context size bug by using max_input_tokens instead of max_tokens

apps/ccusage/src/commands/index.ts, apps/codex/src/run.ts, apps/mcp/src/command.ts
Fix CLI invocation error when using `npx` or `bunx` to run ccusage, codex, and mcp packages.
When executing packages via `npx @ccusage/codex` or `bunx ccusage`, the package managers pass the binary name as the first argument to the CLI. This causes gunshi (our CLI framework) to interpret it as an unknown command, resulting in errors like:
```
Error: Command not found: ccusage-codex
```
Filter out the binary name from argv when it matches the expected binary name:
- `ccusage` for the main ccusage package
- `ccusage-codex` for the codex package  
- `ccusage-mcp` for the MCP server package
- **apps/ccusage**: Filter 'ccusage' from argv when present as first argument
- **apps/codex**: Filter 'ccusage-codex' from argv when present as first argument
- **apps/mcp**: Filter 'ccusage-mcp' from …
=> fix: handle binary name argument when invoked via npx/bunx

apps/ccusage/README.md, apps/codex/README.md, docs/guide/codex/index.md
- Add critical warning about bunx behavior with @ccusage/codex
- Recommend shell alias `ccusage-codex` for convenience
- Document ccusage family of tools in main README
Users were experiencing issues where `bunx @ccusage/codex` would execute an existing 'codex' binary from their PATH instead of the intended npm package. This was due to Bun 1.2.x's bunx behavior with scoped packages.
- Added prominent warning that `bunx @ccusage/codex@latest` **requires** the `@latest` suffix
- Documented the root cause: Bun 1.2.x prioritizes PATH binaries matching the package suffix when given scoped packages
- For `@ccusage/codex`, bunx looks for existing `codex` binaries first (e.g., GitHub Copilot's codex)
- Recommend `ccusage-codex` alias since the full command is long to type
- Provides consistency …
=> docs(codex): add critical bunx warning and shell alias recommendation

apps/ccusage/eslint.config.js, apps/codex/eslint.config.js, apps/mcp/eslint.config.js, docs/eslint.config.js, eslint.config.js, package.json, packages/internal/eslint.config.js, packages/terminal/eslint.config.js, pnpm-lock.yaml, pnpm-workspace.yaml
- Updated @ryoppippi/eslint-config from previous version to 0.4.0
- Removed `svelte: false` from all eslint.config.js files since svelte is now disabled by default
- Updated package dependency to latest version (0.4.0)
- Removed redundant `svelte: false` configuration from:
- Root eslint.config.js
- apps/ccusage/eslint.config.js
- apps/mcp/eslint.config.js
- apps/codex/eslint.config.js
- docs/eslint.config.js
- packages/terminal/eslint.config.js
- packages/internal/eslint.config.js
=> chore: update @ryoppippi/eslint-config to 0.4.0 and remove svelte=false
